[build]
  publish = "build"
  functions = "netlify/functions"
  command = "./deploy.sh"

[build.environment]
  NODE_VERSION = "16"
  TSC_COMPILE_ON_ERROR = "true"
  CI = "false"

# Development settings
[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  envFiles = [".env.development"]  # Specifies to use .env.development during netlify dev

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
